//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fatura.edoksis.net", ConfigurationName="ServiceReference1.FaturaUBLTRServiceSoap")]
    public interface FaturaUBLTRServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/GelenFaturaListeleme", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cikti))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Girdi))]
        TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRCikti GelenFaturaListeleme(TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRGirdi Girdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/GelenFaturaListeleme", ReplyAction="*")]
        System.Threading.Tasks.Task<TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRCikti> GelenFaturaListelemeAsync(TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRGirdi Girdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/GelenUygulamaYanitiListeleme", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cikti))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Girdi))]
        TestConsole.ServiceReference1.GelenUYListelemeUBLTRCikti GelenUygulamaYanitiListeleme(TestConsole.ServiceReference1.GelenUYListelemeUBLTRGirdi Girdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/GelenUygulamaYanitiListeleme", ReplyAction="*")]
        System.Threading.Tasks.Task<TestConsole.ServiceReference1.GelenUYListelemeUBLTRCikti> GelenUygulamaYanitiListelemeAsync(TestConsole.ServiceReference1.GelenUYListelemeUBLTRGirdi Girdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/ZarfGonder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cikti))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Girdi))]
        TestConsole.ServiceReference1.ZarfGonderUBLTRCikti ZarfGonder(TestConsole.ServiceReference1.ZarfGonderUBLTRGirdi Girdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/ZarfGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<TestConsole.ServiceReference1.ZarfGonderUBLTRCikti> ZarfGonderAsync(TestConsole.ServiceReference1.ZarfGonderUBLTRGirdi Girdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/EFaturaFirmalari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cikti))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Girdi))]
        TestConsole.ServiceReference1.EFaturaFirmalariUBLTRCikti EFaturaFirmalari(TestConsole.ServiceReference1.EFaturaFirmalariUBLTRGirdi Girdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fatura.edoksis.net/EFaturaFirmalari", ReplyAction="*")]
        System.Threading.Tasks.Task<TestConsole.ServiceReference1.EFaturaFirmalariUBLTRCikti> EFaturaFirmalariAsync(TestConsole.ServiceReference1.EFaturaFirmalariUBLTRGirdi Girdi);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class GelenFaturaListelemeUBLTRGirdi : Girdi {
        
        private Mukellef mukellefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Mukellef Mukellef {
            get {
                return this.mukellefField;
            }
            set {
                this.mukellefField = value;
                this.RaisePropertyChanged("Mukellef");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class Mukellef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kimlikNOField;
        
        private string tipiField;
        
        private string adiField;
        
        private string soyadiField;
        
        private string webSitesiField;
        
        private string binaNoField;
        
        private string binaAdiField;
        
        private string sokakField;
        
        private string ilceField;
        
        private string sehirField;
        
        private string ulkeField;
        
        private string postaKoduField;
        
        private string vergiDairesiField;
        
        private string telefonField;
        
        private string faxNoField;
        
        private string eMailField;
        
        private string subeField;
        
        private string mahalleField;
        
        private string icKapiNoField;
        
        private string sabitTanimlamaNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KimlikNO {
            get {
                return this.kimlikNOField;
            }
            set {
                this.kimlikNOField = value;
                this.RaisePropertyChanged("KimlikNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Tipi {
            get {
                return this.tipiField;
            }
            set {
                this.tipiField = value;
                this.RaisePropertyChanged("Tipi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
                this.RaisePropertyChanged("Adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Soyadi {
            get {
                return this.soyadiField;
            }
            set {
                this.soyadiField = value;
                this.RaisePropertyChanged("Soyadi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string WebSitesi {
            get {
                return this.webSitesiField;
            }
            set {
                this.webSitesiField = value;
                this.RaisePropertyChanged("WebSitesi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BinaNo {
            get {
                return this.binaNoField;
            }
            set {
                this.binaNoField = value;
                this.RaisePropertyChanged("BinaNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BinaAdi {
            get {
                return this.binaAdiField;
            }
            set {
                this.binaAdiField = value;
                this.RaisePropertyChanged("BinaAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Sokak {
            get {
                return this.sokakField;
            }
            set {
                this.sokakField = value;
                this.RaisePropertyChanged("Sokak");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Ilce {
            get {
                return this.ilceField;
            }
            set {
                this.ilceField = value;
                this.RaisePropertyChanged("Ilce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sehir {
            get {
                return this.sehirField;
            }
            set {
                this.sehirField = value;
                this.RaisePropertyChanged("Sehir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Ulke {
            get {
                return this.ulkeField;
            }
            set {
                this.ulkeField = value;
                this.RaisePropertyChanged("Ulke");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PostaKodu {
            get {
                return this.postaKoduField;
            }
            set {
                this.postaKoduField = value;
                this.RaisePropertyChanged("PostaKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string VergiDairesi {
            get {
                return this.vergiDairesiField;
            }
            set {
                this.vergiDairesiField = value;
                this.RaisePropertyChanged("VergiDairesi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
                this.RaisePropertyChanged("Telefon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FaxNo {
            get {
                return this.faxNoField;
            }
            set {
                this.faxNoField = value;
                this.RaisePropertyChanged("FaxNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Sube {
            get {
                return this.subeField;
            }
            set {
                this.subeField = value;
                this.RaisePropertyChanged("Sube");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Mahalle {
            get {
                return this.mahalleField;
            }
            set {
                this.mahalleField = value;
                this.RaisePropertyChanged("Mahalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string IcKapiNo {
            get {
                return this.icKapiNoField;
            }
            set {
                this.icKapiNoField = value;
                this.RaisePropertyChanged("IcKapiNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SabitTanimlamaNo {
            get {
                return this.sabitTanimlamaNoField;
            }
            set {
                this.sabitTanimlamaNoField = value;
                this.RaisePropertyChanged("SabitTanimlamaNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EFaturaFirmalariUBLTRCikti))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZarfGonderUBLTRCikti))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GelenUYListelemeUBLTRCikti))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GelenFaturaListelemeUBLTRCikti))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class Cikti : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sonucField;
        
        private string mesajField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
                this.RaisePropertyChanged("Sonuc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mesaj {
            get {
                return this.mesajField;
            }
            set {
                this.mesajField = value;
                this.RaisePropertyChanged("Mesaj");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class EFaturaFirmalariUBLTRCikti : Cikti {
        
        private byte[] firmalarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Firmalar {
            get {
                return this.firmalarField;
            }
            set {
                this.firmalarField = value;
                this.RaisePropertyChanged("Firmalar");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class ZarfGonderUBLTRCikti : Cikti {
        
        private System.Guid zarfETTNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ZarfETTN {
            get {
                return this.zarfETTNField;
            }
            set {
                this.zarfETTNField = value;
                this.RaisePropertyChanged("ZarfETTN");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class GelenUYListelemeUBLTRCikti : Cikti {
        
        private UBLTRBelgesi[] yanitlarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public UBLTRBelgesi[] Yanitlar {
            get {
                return this.yanitlarField;
            }
            set {
                this.yanitlarField = value;
                this.RaisePropertyChanged("Yanitlar");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class UBLTRBelgesi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] icerikField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Icerik {
            get {
                return this.icerikField;
            }
            set {
                this.icerikField = value;
                this.RaisePropertyChanged("Icerik");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class GelenFaturaListelemeUBLTRCikti : Cikti {
        
        private UBLTRBelgesi[] faturalarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public UBLTRBelgesi[] Faturalar {
            get {
                return this.faturalarField;
            }
            set {
                this.faturalarField = value;
                this.RaisePropertyChanged("Faturalar");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class Kimlik : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sistemField;
        
        private string kullaniciField;
        
        private string sifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sistem {
            get {
                return this.sistemField;
            }
            set {
                this.sistemField = value;
                this.RaisePropertyChanged("Sistem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                this.kullaniciField = value;
                this.RaisePropertyChanged("Kullanici");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
                this.RaisePropertyChanged("Sifre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EFaturaFirmalariUBLTRGirdi))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZarfGonderUBLTRGirdi))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GelenUYListelemeUBLTRGirdi))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GelenFaturaListelemeUBLTRGirdi))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class Girdi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Kimlik kimlikField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Kimlik Kimlik {
            get {
                return this.kimlikField;
            }
            set {
                this.kimlikField = value;
                this.RaisePropertyChanged("Kimlik");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class EFaturaFirmalariUBLTRGirdi : Girdi {
        
        private System.Nullable<System.DateTime> sorgulamaZamaniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> SorgulamaZamani {
            get {
                return this.sorgulamaZamaniField;
            }
            set {
                this.sorgulamaZamaniField = value;
                this.RaisePropertyChanged("SorgulamaZamani");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class ZarfGonderUBLTRGirdi : Girdi {
        
        private string etiketField;
        
        private UBLTRBelgesi[] belgelerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Etiket {
            get {
                return this.etiketField;
            }
            set {
                this.etiketField = value;
                this.RaisePropertyChanged("Etiket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public UBLTRBelgesi[] Belgeler {
            get {
                return this.belgelerField;
            }
            set {
                this.belgelerField = value;
                this.RaisePropertyChanged("Belgeler");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fatura.edoksis.net")]
    public partial class GelenUYListelemeUBLTRGirdi : Girdi {
        
        private Mukellef mukellefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Mukellef Mukellef {
            get {
                return this.mukellefField;
            }
            set {
                this.mukellefField = value;
                this.RaisePropertyChanged("Mukellef");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FaturaUBLTRServiceSoapChannel : TestConsole.ServiceReference1.FaturaUBLTRServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaturaUBLTRServiceSoapClient : System.ServiceModel.ClientBase<TestConsole.ServiceReference1.FaturaUBLTRServiceSoap>, TestConsole.ServiceReference1.FaturaUBLTRServiceSoap {
        
        public FaturaUBLTRServiceSoapClient() {
        }
        
        public FaturaUBLTRServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaturaUBLTRServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaturaUBLTRServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaturaUBLTRServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRCikti GelenFaturaListeleme(TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRGirdi Girdi) {
            return base.Channel.GelenFaturaListeleme(Girdi);
        }
        
        public System.Threading.Tasks.Task<TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRCikti> GelenFaturaListelemeAsync(TestConsole.ServiceReference1.GelenFaturaListelemeUBLTRGirdi Girdi) {
            return base.Channel.GelenFaturaListelemeAsync(Girdi);
        }
        
        public TestConsole.ServiceReference1.GelenUYListelemeUBLTRCikti GelenUygulamaYanitiListeleme(TestConsole.ServiceReference1.GelenUYListelemeUBLTRGirdi Girdi) {
            return base.Channel.GelenUygulamaYanitiListeleme(Girdi);
        }
        
        public System.Threading.Tasks.Task<TestConsole.ServiceReference1.GelenUYListelemeUBLTRCikti> GelenUygulamaYanitiListelemeAsync(TestConsole.ServiceReference1.GelenUYListelemeUBLTRGirdi Girdi) {
            return base.Channel.GelenUygulamaYanitiListelemeAsync(Girdi);
        }
        
        public TestConsole.ServiceReference1.ZarfGonderUBLTRCikti ZarfGonder(TestConsole.ServiceReference1.ZarfGonderUBLTRGirdi Girdi) {
            return base.Channel.ZarfGonder(Girdi);
        }
        
        public System.Threading.Tasks.Task<TestConsole.ServiceReference1.ZarfGonderUBLTRCikti> ZarfGonderAsync(TestConsole.ServiceReference1.ZarfGonderUBLTRGirdi Girdi) {
            return base.Channel.ZarfGonderAsync(Girdi);
        }
        
        public TestConsole.ServiceReference1.EFaturaFirmalariUBLTRCikti EFaturaFirmalari(TestConsole.ServiceReference1.EFaturaFirmalariUBLTRGirdi Girdi) {
            return base.Channel.EFaturaFirmalari(Girdi);
        }
        
        public System.Threading.Tasks.Task<TestConsole.ServiceReference1.EFaturaFirmalariUBLTRCikti> EFaturaFirmalariAsync(TestConsole.ServiceReference1.EFaturaFirmalariUBLTRGirdi Girdi) {
            return base.Channel.EFaturaFirmalariAsync(Girdi);
        }
    }
}
